Quotes/Controllers/AnnouncementController.cs
using System.Net;
using System.Web.Script.Serialization;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Quotes.FrameworkExtension;
using Quotes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Quotes.DAL;

namespace Quotes.Controllers
{
    public class AnnouncementController : Controller
    {
        // GET: Announcement

        public ActionResult List()
        {

            return PartialView("_Announcements", AnnouncementDAL.GetList());
        }


        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]
        public JsonResult Create()
        {
            try
            {
                AnnouncementDAL.SaveAnnouncement(new AnnouncementModel()
                {
                    Author = User.Identity.Name,
                    RawHtml = "New Text",
                    Title = "New Title"
                }, User.Identity.GetUserId<int>());
                
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = e.Message }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
           
        }

        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]
        public JsonResult Update(AnnouncementModel model)
        {
            if(model == null)
                return Json(new { success = false, message = "Announcement Model data could not be retrieved." }, JsonRequestBehavior.AllowGet);

            try
            {
                model.RawHtml = WebUtility.UrlDecode(model.RawHtml);
                AnnouncementDAL.SaveAnnouncement(model, User.Identity.GetUserId<int>());
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = e.Message }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            
        }

        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]
        public JsonResult Delete(int id)
        {

            try
            {
                AnnouncementDAL.Delete(id);
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = e.Message }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);

        }


        public JsonResult Calendar(string userName = null, string searchText = null, string from = null,
            string to = null, int maxRecords = 1000, string order = "DESC")
        {
            DateTime? fromDate = null;
            DateTime? toDate = null;
            var calendar = new CalendarModel();
            var startTime = new DateTime(1970, 1, 1);
            try
            {
                if (from != null)
                    fromDate = startTime.Add(TimeSpan.FromMilliseconds(Convert.ToDouble(from.Substring(0, 13))));
                if (to != null)
                    toDate = startTime.Add(TimeSpan.FromMilliseconds(Convert.ToDouble(to.Substring(0, 13))));

                var annList = AnnouncementDAL.AnnouncementFilterList(searchText, userName, fromDate, toDate, maxRecords, order);
                calendar = new CalendarModel() { result = new List<CalendarItem>() };
                foreach (var item in annList)
                {
                    var milli =
                        Math.Floor((item.CreationTime - new DateTime(1970, 1, 1)).TotalMilliseconds).ToString();
                    calendar.result.Add(new CalendarItem()
                    {
                        id = item.Id.ToString(),
                        title = item.Title +" - "+ item.Author,
                        start = milli,
                        end = milli,
                        type = "event-important",
                        url = ""
                    });
                }
            }
            catch (Exception e)
            {
                //return json result in error
                calendar.success = 0;
                return Json(calendar, JsonRequestBehavior.AllowGet);
            }

            calendar.success = 1;
            var ouput = JsonConvert.SerializeObject(calendar);
            var json_serializer = new JavaScriptSerializer();
            //return json result in success
            return new JsonResult
            {
                Data = json_serializer.DeserializeObject(ouput),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        public ActionResult Archives()
        {

            return View();
        }

    }
}

Quotes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Quotes.Models;

namespace Quotes.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index(bool? shouldAuth,string returnUrl)
        {
            
            ViewData["OpenAuthorizationPopup"] = shouldAuth;
            ViewData["ReturnUrl"] = returnUrl;

            return View();
        }
        


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult FAQ()
        {

            return View();
        }
    }
}

Quotes/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Quotes/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Quotes/Views/Home/FAQ.cshtml
@{
    ViewBag.Title = "FAQ";
}

<h2>FAQ</h2>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading1">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1">
                    About Account Creation <span class="glyphicon glyphicon-user"></span>
                </a>
            </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading1">
            <div class="panel-body">
                You may want to create an account in order to be able to access all the website content. To do so please fill the registration form right <a href="/Account/Register">here</a>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading2">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="true" aria-controls="collapse2">
                    Posting a Quote <span class="glyphicon glyphicon-pencil"></span>
                </a>
            </h4>
        </div>
        <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
            <div class="panel-body">
                To share your thoughts with other community members go to <a href="/Quote/MyQuotes">your wall</a>, and post a new quote ! You can gain reactions and experience from other users, maybe even win badges if you are popular enough.
            </div>
        </div>
    </div>
</div>

Quotes/Views/Home/Index.cshtml
@using Quotes.Models
@{
    ViewBag.Title = "Home Page";
    var isAdmin = Request.IsAuthenticated && User.IsInRole("Admin");
}

<script src="../../Scripts/ckeditor/ckeditor.js"></script>
<div class="page-header">
    <h1>Welcome to MyQuotes
        @if (isAdmin)
        {

            <button id="newAnn" type="button" class="btn btn-default" style="float:right;" onclick="newAnnouncement()"><span class="glyphicon glyphicon-plus"></span>&ensp;New Announcement</button>
        }</h1>
 
</div>
<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-tag"></span>&ensp;Top Tags of the Day</h3>
            </div>
            <div  class="panel-body">
                <ul id="topTags"></ul>
            </div>
        </div>
        <div class="panel panel-default panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-globe"></span>&ensp;Key Figures</h3>
            </div>
            <div class="panel-body">
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        @{
            Html.RenderAction("List","Announcement");
        }
        <form method="GET" action="/Announcement/Archives">
            <button id="viewArchives" type="submit" class="btn btn-default"><span class="glyphicon glyphicon-folder-open"></span>&ensp;Archives</button>
        </form>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-default panel-success">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-king"></span>&ensp;Top Users of All Time</h3>
            </div>
            <div class="panel-body">
                <ul id="topUsers"></ul>
            </div>
        </div>
        <div class="panel panel-default panel-success">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-king"></span>&ensp;Top Users of Last Month</h3>
            </div>
            <div class="panel-body">
                <ul id="topUsersMonth"></ul>
            </div>
        </div>
        <div class="panel panel-default panel-success" >
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-king"></span>&ensp;Top Users of Last Week</h3>
            </div>
            <div class="panel-body">
                <ul id="topUsersWeek"></ul>
            </div>
        </div>
        <div class="panel panel-default ">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-floppy-saved"></span>&ensp;Last Registered Users</h3>
            </div>
            <div class="panel-body">
                <ul id="lastRegisterUsers"></ul>
            </div>
        </div>
    </div>
</div>


@if (isAdmin)
{
    <script>
        function newAnnouncement() {
            $.post("Announcement/Create",function(data) {
                if (data.success) {
                    location.reload();
                   
                } else {
                    $("#errorMessage").text("There was an error creating a new announcement :" + data.message);
                    $("#errorBox").show();
                }
            });
        }
    </script>
}

<script>
    updateLastUsers();
    updateTopUsers();
    function updateLastUsers() {
        $.get("Users/LastRegistered", function (data) {
            if (data.success) {
                $("#lastRegisterUsers").empty();
                $.each(data.users, function (i) {
                    $("#lastRegisterUsers").append(
                        $('<li>')
                        .html("<a href='Users/Profile?username=" + data.users[i].Username + "' style='color:black'>" + data.users[i].Username + "</a> : " + data.users[i].Label)
                    );
                });
            } else {
                $("#lastRegisterUsers").text("Error loading users...");
                console.log(data.message);
            }
        });

    }

    function updateTopUsers() {
        //TODO put href links onto those usernames to view their profiles
        $.get("Users/Top", function(data) {
            if (data.success) {
                //Top all time
                $("#topUsers").empty();
                $.each(data.users, function (i) {
                    $("#topUsers").append(
                      $('<li>')
                      .html("<a href='Users/Profile?username=" + data.users[i].Username + "' style='color:black'>" + data.users[i].Username + "</a> : " + data.users[i].Points + "&ensp;<span><img src='Content/img/Coin.png' height='16'/></span>")
                  );
                });
                //Top month
                $("#topUsersMonth").empty();
                $.each(data.monthUsers, function (i) {
                    $("#topUsersMonth").append(
                      $('<li>')
                      .html("<a href='Users/Profile?username=" + data.users[i].Username + "' style='color:black'>" + data.users[i].Username + "</a> : " + data.users[i].Points + "&ensp;<span><img src='Content/img/Coin.png' height='16'/></span>")
                  );
                });
                //Top week
                $("#topUsersWeek").empty();
                $.each(data.weekUsers, function (i) {
                    $("#topUsersWeek").append(
                      $('<li>')
                      .html("<a href='Users/Profile?username=" + data.users[i].Username + "' style='color:black'>" + data.users[i].Username + "</a> : " + data.users[i].Points + "</a>&ensp;<span><img src='Content/img/Coin.png' height='16'/></span>")
                  );
                });
            } else {
                $("#topUsers").text("Error loading users...");
                $("#topUsersMonth").text("Error loading users...");
                $("#topUsersWeek").text("Error loading users...");
                console.log(data.message);
            }
        });
    }

    setInterval(updateLastUsers, 60000);
    setInterval(updateTopUsers, 3600000);


</script>

Quotes/Views/Home/_Announcements.cshtml
@{
    var isAdmin = Request.IsAuthenticated && User.IsInRole("Admin");
}
@model List<Quotes.Models.AnnouncementModel>

@foreach (var ann in Model)
{
    if (!isAdmin && ann.Status != 1) //Not displaying Announcements that are not published for non-admin users
    {
        continue;
    }
    <div class="panel panel-default panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title col-lg-12">@ann.Title</h3>
            <input name="title@(ann.Id)" id="title@(ann.Id)" type="text" maxlength="256" value="Announcements" style="display: none" />
            @if (isAdmin)
            {
                <button id="title@(ann.Id)-edit" type="button" class="btn-edit" onclick="editTitle('title@(ann.Id)')"><span class="glyphicon glyphicon-pencil"></span></button>
                <button id="title@(ann.Id)-close" type="button" class="btn-edit" onclick="closeTitle('title@(ann.Id)')" style="display: none"><span class="glyphicon glyphicon-remove"></span></button>
                <button id="title@(ann.Id)-save" type="button" class="btn-edit" onclick="saveTitle('title@(ann.Id)')" style="display: none"><span class="glyphicon glyphicon-ok"></span></button>
            }
        </div>
        <div class="panel-body">
            <form>
                <div name="@ann.Id" id="announce1" rows="12" cols="80">
                    @ann.RawHtml
                </div>
            </form>
            @if (isAdmin)
            {
                <button id="announce@(ann.Id)-cksave" type="button" class="btn btn-default pull-right" onclick="saveAnnouncement('announce@(ann.Id)')" style=" display: none">Save</button>
                <button id="announce@(ann.Id)-ckopen" type="button" class="btn btn-default pull-right" onclick="initEditor('announce@(ann.Id)')">Edit</button>
                <button id="announce@(ann.Id)-ckclose" type="button" class="btn btn-default pull-right" onclick="closeEditor('announce@(ann.Id)')" style="display: none">Cancel</button>
            }
        </div>
        <div class="panel-footer">
            Author : @ann.Author - @ann.CreationTime
        </div>
    </div>
}


@if (isAdmin)
{

    <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        function initEditor(id) {
            if (CKEDITOR.instances[id])
                CKEDITOR.remove(CKEDITOR.instances[id]);
            CKEDITOR.replace(id);
            $("#" + id + "-ckopen").hide();
            $("#" + id + "-ckclose").show();
            $("#" + id + "-cksave").show();
        }

        // Close ck editor dialog
        function closeEditor(id) {
            $("#cke_" + id).remove();
            $("#" + id).show();
            $("#" + id).removeAttr('style');

            $("#" + id + "-cksave").hide();
            $("#" + id + "-ckclose").hide();
            $("#" + id + "-ckopen").show();
        }

        // Save announcement in database and update UI
        function saveAnnouncement(id) {
            CKEDITOR.instances[id].updateElement();

            //TODO submit form

            closeEditor(id);
        }

        function editTitle(id) {
            $("#" + id + "-edit").hide();
            $("#" + id + "-close").show();
            $("#" + id + "-save").show();
        }

        function closeTitle(id) {
            $("#" + id + "-save").hide();
            $("#" + id + "-close").hide();
            $("#" + id + "-edit").show();
        }

        function saveTitle(id) {
            $("#title" + id).val();
        }

    </script>
}