Quotes/Controllers/QuoteController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Quotes.DAL;
using Quotes.FrameworkExtension;
using Quotes.Models;
using System;
using System.Linq;

namespace Quotes.Controllers
{
    public class QuoteController : Controller
    {
        [CustomAuthorize]
        public ActionResult MyQuotes()
        {
            var userId = User.Identity.GetUserId<int>();
            ViewData["lastPostDate"] = QuoteDAL.CheckLastUserPostDate(userId);
            return View(QuoteDAL.FindUserQuotes(userId));
        }

        [HttpPost]
        [CustomAuthorize]
        public ActionResult PostQuote(string text)
        {
            //Save new quote in database
            QuoteDAL.SaveQuote(new QuoteModel
            {
                QuoteText = text,
                UserId = User.Identity.GetUserId<int>()
            });

            //Refresh page
            return RedirectToAction("MyQuotes");
        }

        [HttpPost]
        public ActionResult SearchQuote(string searchText)
        {
            if (string.IsNullOrEmpty(searchText))
            {
                return View("SearchResult",null);
            }

            ViewData["research"] = searchText;
            //search quote in database and Load result page
            return View("SearchResult", QuoteDAL.FindQuotes(searchText));
        }

        //Search Api
        public JsonResult Search(string searchText, string userName, string from, string to, int maxRecords = 1000,
            string order = "DESC")
        {
            DateTime? fromDate = null;
            DateTime? toDate = null;
            var result = new List<UserQuoteModel>();

            try
            {
                if (from != null)
                    fromDate = DateTime.Parse(from);
                if (to != null)
                    toDate = DateTime.Parse(to);

                result = QuoteDAL.QuoteFilterList(searchText, userName, fromDate, toDate, maxRecords, order);
            }
            catch (Exception e)
            {
                return Json(new {success = false, responseText = e});
            }


            //search quote in database and Load result page
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Method to return Calendar model Json for the calendar view of quotes
        /// </summary>
        /// <param name="userName"></param>
        /// <param name="searchText"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="maxRecords"></param>
        /// <param name="order"></param>
        /// <returns></returns>
        public JsonResult SearchForCalendar(string userName, string searchText = null, string from = null,
            string to = null, int maxRecords = 1000, string order = "DESC")
        {
            DateTime? fromDate = null;
            DateTime? toDate = null;
            var calendar = new CalendarModel();
            var startTime = new DateTime(1970, 1, 1);
            try
            {
                if (from != null)
                    fromDate = startTime.Add(TimeSpan.FromMilliseconds(Convert.ToDouble(from.Substring(0,13))));
                if (to != null)
                    toDate = startTime.Add(TimeSpan.FromMilliseconds(Convert.ToDouble(to.Substring(0, 13))));


                var quoteList = QuoteDAL.QuoteFilterList(searchText, userName, fromDate, toDate, maxRecords, order);
                calendar = new CalendarModel() {result = new List<CalendarItem>()};
                foreach (var item in quoteList)
                {
                    var milli =
                        Math.Floor((item.Quote.OriginalDate - new DateTime(1970, 1, 1)).TotalMilliseconds).ToString();
                    calendar.result.Add(new CalendarItem()
                    {
                        id = item.Quote.QuoteId.ToString(),
                        title = item.Quote.QuoteText,
                        start = milli,
                        end = milli,
                        type = "event-important",
                        url = ""
                    });
                }
            }
            catch (Exception)
            {
                //return json result in error
                calendar.success = 0;
                return Json(calendar, JsonRequestBehavior.AllowGet);
            }

            calendar.success = 1;
            var ouput = JsonConvert.SerializeObject(calendar);
            var json_serializer = new JavaScriptSerializer();
            //return json result in success
            return new JsonResult
            {
                Data = json_serializer.DeserializeObject(ouput),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        [CustomAuthorize]
        public ActionResult Calendar()
        {

            return View();
        }

        [CustomAuthorize]
        public JsonResult MyCalendar(string userName, string searchText = null, string from = null,
            string to = null, int maxRecords = 1000, string order = "DESC")
        {

            return SearchForCalendar(User.Identity.Name, searchText,from,to,maxRecords,order);
        }

        [HttpPost]
        [CustomAuthorize]
        public JsonResult TagQuote(int quoteId, string tag)
        {
            //Increment a Tag on the quote (like, dislike or any other tag), return the json result of the request.
            try
            {
                QuoteDAL.TagQuote(new QuoteModel() {QuoteId = quoteId, UserId = User.Identity.GetUserId<int>()}, tag);
            }
            catch (Exception e)
            {

                return Json(new { success = false, message = e.Message}, JsonRequestBehavior.AllowGet);
            }
            return Json(new{success = true}, JsonRequestBehavior.AllowGet);
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult AdminQuoteList()
        {
            return View(QuoteDAL.FindQuotes("").Select(x => new UserQuoteViewModel(x)).ToList());
        }

        [CustomAuthorize]
        public ActionResult MyFeed()
        {
            return View();
        }

        [CustomAuthorize]
        public PartialViewResult Random()
        {
            return PartialView("_Quote",QuoteDAL.FindRandomQuote());
        }

    }
}

Quotes/Views/Quote/AdminQuoteList.cshtml
@using Quotes.Models
@model List<UserQuoteViewModel>
@{
    ViewBag.Title = "AdminList";
}

<h2>AdminList</h2>

<div class="row">
    <div class="col-lg-12">
        @{
            var grid = new WebGrid(canPage: true, canSort: true, defaultSort: "QuoteDate", pageFieldName: "Page", sortDirectionFieldName: "SortDir", sortFieldName: "SortField");
            grid.Bind(Model, autoSortAndPage: false, rowCount: Model.Count);
        }
        @{
            var columns = new List<WebGridColumn>
                {
                    grid.Column("QuoteId", "Quote Id"),
                    grid.Column("QuoteDate", "Submission date"),
                    grid.Column("Username", "Author"),
                    grid.Column("QuoteText", "Text")
                };

            @grid.GetHtml(htmlAttributes: new { id = "AdminQuoteList" }, tableStyle: "table table-striped table-bordered", columns: columns)
        }
    </div>
</div>

Quotes/Views/Quote/Calendar.cshtml
@{
    ViewBag.Title = "Calendar";
}
<script>
    loadFromURL = '/Quote/MyCalendar';
</script>
@Scripts.Render("~/bundles/Calendar")
@Styles.Render("~/bundles/CalendarStyle")

<h2>Calendar</h2>

<div class="page-header">
    <div class="pull-right form-inline">
        <div class="btn-group">
            <button class="btn btn-primary" data-calendar-nav="prev"><< Prev</button>
            <button class="btn" data-calendar-nav="today">Today</button>
            <button class="btn btn-primary" data-calendar-nav="next">Next >></button>
        </div>
        <div class="btn-group">
            <button class="btn btn-warning" data-calendar-view="year">Year</button>
            <button class="btn btn-warning active" data-calendar-view="month">Month</button>
            <button class="btn btn-warning" data-calendar-view="week">Week</button>
        </div>
    </div>
    <h3></h3>
</div>

<div class="row">
    <div id="calendar"></div>
</div>

Quotes/Views/Quote/MyFeed.cshtml
@{
    ViewBag.Title = "MyFeed";
}

<h2>My Feed</h2>


<div class="text-center" style="color:white;">
    Today
</div>
<hr>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Username 1
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
                Quote
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingTwo">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Username 2
                </a>
            </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
            <div class="panel-body">
                Quote
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingThree">
            <h4 class="panel-title">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Username 3
                </a>
            </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
            <div class="panel-body">
                Quote
            </div>
        </div>
    </div>
</div>

@{
    
    DateTime input = DateTime.Now;
    int delta =  input.DayOfWeek - DayOfWeek.Monday;
     
}
@for (int i = 1; i < delta+1; i++)
{
    <div class="text-center" style="color:white;">
        @input.AddDays(-i).DayOfWeek
    </div>
    <hr>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading@(i)">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse@(i)" aria-expanded="true" aria-controls="collapse@(i)">
                        Username 1
                    </a>
                </h4>
            </div>
            <div id="collapse@(i)" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading@(i)">
                <div class="panel-body">
                    Quote
                </div>
            </div>
        </div>
    </div>

}

Quotes/Views/Quote/MyQuotes.cshtml
@using Quotes.Models
@{
    ViewBag.Title = "MyQuotes";
    var lastPostDate = (DateTime?)ViewData["lastPostDate"];
}
@model UserQuoteListModel
@Scripts.Render("~/bundles/Quotes")

<h1>My Quotes</h1>
@if (lastPostDate != null)
{
    <h3>Hello! You have <span class="label label-default" id="timer"></span> remaining for Today's post!</h3>
}
else
{
    <h3>Done for today, see you tomorow!</h3>
}

<div class="row">
    <div class="col-lg-12">
        @using(Html.BeginForm("PostQuote","Quote",FormMethod.Post)){

            <div id="postQuote" class="input-group input-group-lg">
                <span class="input-group-addon">"</span>
                <input id="text" name="text" type="text" class="form-control quote-form" placeholder="Express yourself...">
                <span class="input-group-addon">"</span>
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Post!</button>
                </span>
            </div>
        }
        
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <ul class="media-list">
            @if (Model != null && Model.UserQuotes != null)
            {
                foreach (var item in Model.UserQuotes)
                {
                    <li class="media">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object" src="@Model.User.ProfileIconPath" alt="">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">@item.OriginalDate - Reactions : <span class="badge">@item.SumActivity()</span></h4>                                
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    @item.QuoteText
                                </div>
                                <div class="panel-footer">
                                    <span class="badge badge-like" id="badge-like-@(item.QuoteId)">@item.Likes</span>
                                    <button id="like" type="button" title="Like!" class="btn btn-default btn-like" onclick="TagQuote(@item.QuoteId,'Like')"><span class="glyphicon glyphicon-thumbs-up"></span></button>
                                    <span class="badge badge-dislike">@item.Dislikes</span>
                                    <button id="dislike" type="button" title="Dislike!" class="btn btn-default btn-dislike" onclick="TagQuote(@item.QuoteId,'Dislike')"><span class="glyphicon glyphicon-thumbs-down"></span></button>
                                    <span class="badge badge-star">@item.Stars</span>
                                    <button id="favorite" type="button" title="Add to Favorites!" class="btn btn-default btn-star" onclick="TagQuote(@item.QuoteId,'Star')"><span class="glyphicon glyphicon-star-empty"></span></button>
                                    <button id="tag" type="button" title="Add a Tag!" class="btn btn-default btn-tag" onclick=""><span class="glyphicon glyphicon-tag"></span></button>   
                                    <button id="report" type="button" title="Report Quote!" class="btn btn-default btn-flag" style="float:right" onclick="TagQuote(@item.QuoteId,'Flag')"><span class="glyphicon glyphicon-flag"></span></button>        
                                </div>
                            </div>
                        </div>
                    </li>
                }
            }           
        </ul>
    </div>
</div>

@if (lastPostDate != null)
{
    <script>
        var end = new Date();
        end.setHours(23, 59, 59, 999);
        setInterval(function() {
            var remaining = getTimeRemaining(end);
            if (remaining.hours < 8) {
                $('#timer').removeClass('label-default').addClass('label-warning');
                if (remaining.hours < 1) {
                    $('#timer').removeClass('label-warning').addClass('label-danger');
                    if(remaining.hours <=0 && remaining.minutes <=0 && remaining.seconds <=0)
                        location.reload();
                }
            } 
            $("#timer").text(remaining.hours + " Hour(s) " + remaining.minutes + " Minute(s) " + remaining.seconds + " Second(s)");

        }, 1000);

        function getTimeRemaining(endtime) {
            var t = Date.parse(endtime) - Date.parse(new Date());
            var seconds = Math.floor((t / 1000) % 60);
            var minutes = Math.floor((t / 1000 / 60) % 60);
            var hours = Math.floor((t / (1000 * 60 * 60)) % 24);
            var days = Math.floor(t / (1000 * 60 * 60 * 24));
            return {
                'total': t,
                'days': days,
                'hours': hours,
                'minutes': minutes,
                'seconds': seconds
            };
        }
    </script>
}
else
{
     <script>
        $("#postQuote :input").attr("disabled", true);
     </script>
}

Quotes/Views/Quote/SearchResult.cshtml
@using Quotes.Models
@model List<UserQuoteModel>
@{
    ViewBag.Title = "Search";
}
<h2>Search Result : </h2>
@if (Model != null && Model.Count > 0)
{
    <div class="row">
        <div class="col-lg-12">

            <ul class="media-list">
                @foreach (var item in Model)
                {
                    <li class="media">
                        <div class="media-left">
                            <a id="userInfo" href="/Users/Profile?username=@item.User.UserName">
                                <img class="media-object" src="/Content/Users/Images/@(item.Quote.UserId).jpg" alt="@item.User.UserName" height="128" width="128">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 id="quoteTitle" class="media-heading">@item.Quote.OriginalDate <a href="#">Reactions <span class="badge">42</span></a></h4>
                            <div class="panel panel-default">
                                <div id="quoteText" class="panel-body">
                                    @item.Quote.QuoteText
                                </div>
                                <div class="panel-footer">
                                    <span class="badge badge-like">@item.Quote.Likes</span>
                                    <button id="like" type="button" title="Like!" class="btn btn-default btn-like" onclick="TagQuote(@item.Quote.QuoteId, 'Like') "><span class="glyphicon glyphicon-thumbs-up"></span></button>
                                    <span class="badge badge-dislike">@item.Quote.Dislikes</span>
                                    <button id="dislike" type="button" title="Dislike!" class="btn btn-default btn-dislike" onclick="TagQuote(@item.Quote.QuoteId, 'Dislike') "><span class="glyphicon glyphicon-thumbs-down"></span></button>
                                    <span class="badge badge-star">@item.Quote.Stars</span>
                                    <button id="favorite" type="button" title="Add to Favorites!" class="btn btn-default btn-star" onclick="TagQuote(@item.Quote.QuoteId, 'Star') "><span class="glyphicon glyphicon-star-empty"></span></button>
                                    <button id="report" type="button" title="Report Quote!" class="btn btn-default btn-flag" style="float: right" onclick="TagQuote(@item.Quote.QuoteId, 'Flag') "><span class="glyphicon glyphicon-flag"></span></button>
                                </div>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
    <script>
        /* Highlight the Occurences of the Search. */
        var str = "@ViewData["research"]";
        $("#quoteTitle").html( $("#quoteTitle").html().replace(str,"<span class='highlight'>"+str+"</span>"));
        $("#quoteText").html($("#quoteText").text().replace(str, "<span class='highlight'>" + str + "</span>"));

    </script>
    <style>
        .highlight {
            background-color: khaki;
        }
    </style>
}
else
{
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <p><span class="glyphicon glyphicon-remove"></span>&ensp;Sorry, we could not find what you were looking for!</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <button id="randomSearch" type="button" title="Find Random Quote!" class="btn btn-default btn-like" onclick="loadRandomQuote()"><span class="glyphicon glyphicon-random"></span>&ensp;Find a Random Quote</button>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <ul id="randomQuote" class="media-list"></ul>
        </div>
    </div>
    <script type="text/javascript">
        function loadRandomQuote() {
            $.get("/Quote/Random", function (data) {
                if (data) {
                    $("#randomQuote").html(data)
                } else {
                    $("#errorMessage").text("There was an error loading a random quote");
                    $("#errorBox").show();
                }
            });

        }
    </script>
}

Quotes/Views/Quote/SearchResultQuotes.cshtml
@using Quotes.Models
@model List<UserQuoteModel>

<h2>Search Result : </h2>

<div class="row">
    <div class="col-lg-12">
        <ul class="media-list">
            @if (@Model != null)
            {
                foreach (var item in @Model)
                {
                    <li class="media">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object" src="@item.User.ProfileIconPath" alt="">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">@item.Quote.OriginalDate <a href="#">Reactions <span class="badge">42</span></a></h4>
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    @item.Quote.QuoteText
                                </div>
                                <div class="panel-footer">
                                    <span class="badge badge-like">@item.Quote.Likes</span>
                                    <button id="like" type="button" title="Like!" class="btn btn-default btn-like" onclick=" TagQuote(@item.Quote.QuoteId, 'Like') "><span class="glyphicon glyphicon-thumbs-up"></span></button>
                                    <span class="badge badge-dislike">@item.Quote.Dislikes</span>
                                    <button id="dislike" type="button" title="Dislike!" class="btn btn-default btn-dislike" onclick=" TagQuote(@item.Quote.QuoteId, 'Dislike') "><span class="glyphicon glyphicon-thumbs-down"></span></button>
                                    <span class="badge badge-star">@item.Quote.Favorites</span>
                                    <button id="favorite" type="button" title="Add to Favorites!" class="btn btn-default btn-star" onclick=" TagQuote(@item.Quote.QuoteId, 'Star') "><span class="glyphicon glyphicon-star-empty"></span></button>
                                    <button id="report" type="button" title="Report Quote!" class="btn btn-default btn-flag" style="float: right" onclick=" TagQuote(@item.Quote.QuoteId, 'Flag') "><span class="glyphicon glyphicon-flag"></span></button>
                                </div>
                            </div>
                        </div>
                    </li>
                }
            }
            else
            {
                <p>Sorry, we could not find what you were looking for.</p>
            }
        </ul>
    </div>
</div>

Quotes/Views/Quote/_Quote.cshtml
@using Quotes.Models
@model QuoteModel

@if (Model != null)
{
    <li class="media">
        <div class="media-body">
            <h4 class="media-heading">@Model.OriginalDate <a href="#">Reactions <span class="badge">42</span></a></h4>
            <div class="panel panel-default">
                <div class="panel-body">
                    @Model.QuoteText
                </div>
                <div class="panel-footer">
                    <span class="badge badge-like">@Model.Likes</span>
                    <button id="like" type="button" title="Like!" class="btn btn-default btn-like" onclick="QuoteLike(@Model.QuoteId)"><span class="glyphicon glyphicon-thumbs-up"></span></button>
                    <span class="badge badge-dislike">@Model.Dislikes</span>
                    <button id="dislike" type="button" title="Dislike!" class="btn btn-default btn-dislike" onclick="QuoteDislike(@Model.QuoteId)"><span class="glyphicon glyphicon-thumbs-down"></span></button>
                    <span class="badge badge-star">@Model.Stars</span>
                    <button id="favorite" type="button" title="Add to Favorites!" class="btn btn-default btn-star" onclick="QuoteStar(@Model.QuoteId)"><span class="glyphicon glyphicon-star-empty"></span></button>
                    <button id="report" type="button" title="Report Quote!" class="btn btn-default btn-flag" style="float:right"><span class="glyphicon glyphicon-flag"></span></button>
                </div>
            </div>
        </div>
    </li>

}